---
- name: Collect extended facts and send to cache
  hosts: all
  gather_facts: true
  become: true
  vars:
    debug: false
    log: false
  tasks:
    - name: Collect list of installed packages
      ansible.builtin.package_facts:
        manager: auto
      tags: packages

    - name: Collect services
      ansible.builtin.service_facts: {}
      tags: services

    - name: Collect active TCP/UDP ports
      community.general.listen_ports_facts: {}
      tags: ports

    - name: Collect processes
      tags: process
      block:
        - name: Collect processes - Listing processes except kernel threads
          ansible.builtin.shell: >
            ps -eo pid=,comm=,args= --no-headers
            | awk '{
              pid = $1;
              comm = $2;
              $1 = ""; $2 = "";
              sub(/^ +/, "", $0);
              if ($0 ~ /^\[.*\]$/) next;               # ignora args como "[kworker/...]" etc.
              gsub(/\\/, "\\\\", $0);                  # escapa barras invertidas
              gsub(/"/, "\\\"", $0);                   # escapa aspas duplas
              printf("{\"pid\": \"%s\", \"command\": \"%s\", \"args\": \"%s\"}\n", pid, comm, $0);
            }'
          register: ps_output
          changed_when: false
          tags: processes

        - name: Collecting Processes - Creating facts with the Process List
          ansible.builtin.set_fact:
            cacheable: true
            processes: "{{ ps_output.stdout_lines | map('from_json') | list }}"
          tags: processes

# ------------------------- JAVA -------------------------

    - name: Check for Java processes
      ansible.builtin.set_fact:
        cacheable: true
        has_java_processes: "{{ processes | selectattr('args', 'search', 'java') | list | length > 0 }}"
      tags: java

    - name: Collects information from Java processes
      ansible.builtin.import_tasks:
        file: java/java.yaml
      when: has_java_processes
      tags: java

# ---------------------- WEBSERVERS ----------------------

    - name: Check for webservers processes
      ansible.builtin.set_fact:
        cacheable: true
        has_webservers_processes: "{{ processes | selectattr('command', 'in', ['httpd', 'nginx']) | list | length > 0 }}"
      tags: webservers

    - name: Collects information from webservers processes
      ansible.builtin.import_tasks:
        file: webservers/webservers.yaml
      when: has_webservers_processes
      tags: webservers
